import { Brain, MessageCircle, Network, Rabbit } from "lucide-react";
import { PageIntro, SiteFooter, SiteHeader } from "../site-shell";
const areas=[
  {icon:MessageCircle,title:"Signals and sexual selection",text:"We study the design, information content and evolution of visual, chemical and dynamic signals. Current work examines complex displays, colour signals, honest signalling and deimatic displays across lizard lineages."},
  {icon:Brain,title:"Cognition and brain evolution",text:"We investigate learning, behavioural flexibility, spatial cognition and the evolution of brain size and structure. Comparative projects ask how ecology, sociality and complex signalling shape cognition."},
  {icon:Network,title:"Sociality and family living",text:"Australian Egernia-group lizards provide a powerful model for understanding social plasticity, cooperation and the evolutionary origins of kin-based family groups."},
  {icon:Rabbit,title:"Behaviour in changing environments",text:"Our research also explores invasive species, urban ecology, climate responses, reproductive strategies and how animals adjust their behaviour when environments change."},
];
export default function Research(){return <><SiteHeader/><main><PageIntro kicker="Our research" title="Why animals behave the way they do"><p>We use behaviour to connect mechanisms operating within individuals to broader ecological and evolutionary processes.</p></PageIntro><section className="page-shell research-visual"><img src="/images/Phrynocephalus.jpg" alt="Toad-headed agamas displaying and moving across desert habitat" width="960" height="540"/></section><section className="section page-shell research-grid">{areas.map(({icon:Icon,title,text})=><article className="research-card" key={title}><Icon/><h2>{title}</h2><p>{text}</p></article>)}</section><section className="section section-soft"><div className="page-shell methods-row"><div><p className="eyebrow">How we work</p><h2>Fieldwork, experiments and comparative biology</h2></div><p>We observe animals in natural populations, run controlled behavioural experiments, measure signals and performance, and use phylogenetic comparative methods to test evolutionary hypotheses across species.</p></div></section></main><SiteFooter/></>}
